export const defaultCategories = [
  { id: "c_men", name: "Men", slug: "men", parentId: null, sortOrder: 0, featured: true, visible: true, status: "active", description: "Menswear" },
  { id: "c_app", name: "Apparel", slug: "apparel", parentId: "c_men", sortOrder: 0, featured: true, visible: true, status: "active", description: "Tops, bottoms and layers" },
  { id: "c_tops", name: "Tops", slug: "tops", parentId: "c_app", sortOrder: 0, featured: false, visible: true, status: "active", description: "" },
  { id: "c_bottoms", name: "Bottoms", slug: "bottoms", parentId: "c_app", sortOrder: 1, featured: false, visible: true, status: "active", description: "" },
  { id: "c_out", name: "Outerwear", slug: "outerwear", parentId: "c_men", sortOrder: 1, featured: false, visible: true, status: "active", description: "Shells and jackets" },
  { id: "c_acc", name: "Accessories", slug: "accessories", parentId: null, sortOrder: 1, featured: true, visible: true, status: "active", description: "Caps, socks and small goods" },
  { id: "c_bags", name: "Bags", slug: "bags", parentId: null, sortOrder: 2, featured: false, visible: true, status: "active", description: "" }
];

export const defaultWarehouses = [
  { id: "w1", name: "Kathmandu DC", code: "WH-KTM" },
  { id: "w2", name: "Pokhara Store", code: "WH-PKR" }
];

export const defaultProducts = [
  {
    id: "m1",
    name: "Monolith Tee",
    slug: "monolith-tee",
    sku: "ZYL-APP-00001",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["tee", "core"],
    price: 180000,
    basePrice: 180000,
    mrp: 220000,
    cost: 90000,
    status: "published",
    labels: { featured: false, trending: false, newArrival: true, bestSelling: true },
    description: "240 GSM heavy jersey tee with drop-shoulder fit and high ribbed collar.",
    options: { Colour: ["Black", "White"], Size: ["S", "M", "L"] },
    images: [
      { url: "/assets/ea97fe30fd8d1dfc.q.jpg", alt: "Monolith Tee in Black", isFeatured: true },
      { url: "/assets/09789ab9b9e151f6.q.jpg", alt: "Monolith Tee in White", isFeatured: false }
    ]
  },
  {
    id: "m2",
    name: "Grid Hoodie",
    slug: "grid-hoodie",
    sku: "ZYL-APP-00002",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["hoodie", "fleece"],
    price: 380000,
    basePrice: 380000,
    mrp: 450000,
    cost: 190000,
    status: "published",
    labels: { featured: true, trending: true, newArrival: false, bestSelling: false },
    description: "420 GSM loopback French terry hoodie with double-layer hood.",
    options: { Colour: ["Black"], Size: ["S", "M", "L"] },
    images: [
      { url: "/assets/eeac2757b9ee2e46.q.jpg", alt: "Grid Hoodie in Black", isFeatured: true }
    ]
  },
  {
    id: "m3",
    name: "Aperture Cap",
    slug: "aperture-cap",
    sku: "ZYL-ACC-00001",
    categoryId: "c_acc",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["cap", "hat"],
    price: 150000,
    basePrice: 150000,
    mrp: 180000,
    cost: 65000,
    status: "published",
    labels: { featured: true, trending: false, newArrival: true, bestSelling: false },
    description: "Low-profile six-panel cap in water-repellent nylon taslan.",
    options: { Colour: ["Black"], Size: ["One size"] },
    images: [
      { url: "/assets/7f3fd1f72139111d.q.jpg", alt: "Aperture Cap in Black", isFeatured: true }
    ]
  },
  {
    id: "m4",
    name: "Ledger Tote",
    slug: "ledger-tote",
    sku: "ZYL-BAG-00001",
    categoryId: "c_bags",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["bag", "canvas"],
    price: 220000,
    basePrice: 220000,
    mrp: 260000,
    cost: 95000,
    status: "published",
    labels: { featured: false, trending: true, newArrival: false, bestSelling: false },
    description: "16oz heavy cotton canvas tote with interior zipped pocket.",
    options: { Colour: ["Natural", "Black"], Size: ["One size"] },
    images: [
      { url: "/assets/e282ebdc1a55d0be.q.jpg", alt: "Ledger Tote in Natural", isFeatured: true }
    ]
  },
  {
    id: "m5",
    name: "Contour Jacket",
    slug: "contour-jacket",
    sku: "ZYL-OUT-00001",
    categoryId: "c_out",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["jacket"],
    price: 720000,
    basePrice: 720000,
    mrp: 860000,
    cost: 420000,
    status: "published",
    labels: { featured: true, trending: false, newArrival: false, bestSelling: false },
    description: "Cropped shell with taped seams.",
    options: { Colour: ["Black"], Size: ["S", "M", "L"] },
    images: [
      { url: "/assets/57e8f8ec76e792b1.q.jpg", alt: "Contour Jacket", isFeatured: true },
      { url: "/assets/e2a028dd8bd0e7b5.q.jpg", alt: "Contour Jacket detail", isFeatured: false }
    ]
  },
  {
    id: "m6",
    name: "Frame Trousers",
    slug: "frame-trousers",
    sku: "ZYL-APP-00003",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Unisex",
    season: "SS26",
    tags: ["trousers"],
    price: 300000,
    basePrice: 300000,
    mrp: 360000,
    cost: 150000,
    status: "published",
    labels: { featured: false, trending: false, newArrival: false, bestSelling: false },
    description: "Straight leg with articulated knee.",
    options: { Colour: ["Black"], Size: ["30", "32", "34"] },
    images: [
      { url: "/assets/9a83a5f92f7a34f6.q.jpg", alt: "Frame Trousers", isFeatured: true },
      { url: "/assets/19eee9f8e07093fd.q.jpg", alt: "Frame Trousers detail", isFeatured: false }
    ]
  },
  {
    id: "p_knit_shirt",
    name: "Textured Knitted Shirt",
    slug: "textured-knitted-shirt",
    sku: "ZYL-TOP-KNIT-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["knit", "shirt", "summer"],
    price: 175000,
    basePrice: 175000,
    mrp: 235000,
    cost: 85000,
    status: "published",
    labels: { newArrival: true, featured: true, bestSelling: false },
    description: "An open-weave knit shirt with a relaxed boxy cut. Breathable texture that layers cleanly over a plain tee for everyday wear.",
    options: { Colour: ["Oatmeal", "Black"], Size: ["S", "M", "L", "XL"] },
    images: [
      { url: "/assets/98eab38550301ca9.q.jpg", alt: "Textured Knitted Shirt", isFeatured: true },
      { url: "/assets/248028cbf9d4d390.q.jpg", alt: "Textured Knitted Shirt detail", isFeatured: false }
    ]
  },
  {
    id: "p_trench_coat",
    name: "Structured Trench Coat",
    slug: "structured-trench-coat",
    sku: "ZYL-OUT-TRN-01",
    categoryId: "c_out",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["trench", "coat", "outerwear"],
    price: 630000,
    basePrice: 630000,
    mrp: 840000,
    cost: 320000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "A sharply tailored trench in a water-resistant twill. Structured shoulders and a clean drape built for the city.",
    options: { Colour: ["Khaki", "Black"], Size: ["M", "L", "XL"] },
    images: [
      { url: "/assets/ee2608e46a586391.q.jpg", alt: "Structured Trench Coat", isFeatured: true },
      { url: "/assets/0e72c7de7ec1a38e.q.jpg", alt: "Structured Trench Coat detail", isFeatured: false }
    ]
  },
  {
    id: "p_denim_overalls",
    name: "Mini Denim Overalls",
    slug: "mini-denim-overalls",
    sku: "ZYL-BOT-OVR-01",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Kids",
    season: "SS26",
    tags: ["overalls", "denim", "kids"],
    price: 135000,
    basePrice: 135000,
    mrp: 180000,
    cost: 60000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "Kid-sized denim overalls in a mid-blue wash. Reinforced stitching and adjustable straps for growing frames.",
    options: { Colour: ["Indigo"], Size: ["4Y", "6Y", "8Y", "10Y"] },
    images: [
      { url: "/assets/e282ebdc1a55d0be.q.jpg", alt: "Mini Denim Overalls", isFeatured: true },
      { url: "/assets/08accf483615b0df.q.jpg", alt: "Mini Denim Overalls detail", isFeatured: false }
    ]
  },
  {
    id: "p_riviera_shirt",
    name: "Riviera Collar Shirt",
    slug: "riviera-collar-shirt",
    sku: "ZYL-TOP-RIV-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["camp", "shirt", "gauze"],
    price: 135000,
    basePrice: 135000,
    mrp: 180000,
    cost: 62000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "A camp-collar shirt in crinkled cotton gauze. Light, airy and made for warm afternoons.",
    options: { Colour: ["White", "Sage"], Size: ["XS", "S", "M", "L"] },
    images: [
      { url: "/assets/a22003dc69fc0fc1.q.jpg", alt: "Riviera Collar Shirt", isFeatured: true },
      { url: "/assets/b3a1fbdacd69bcda.q.jpg", alt: "Riviera Collar Shirt detail", isFeatured: false }
    ]
  },
  {
    id: "p_jersey_tee",
    name: "Stretch Jersey Tee",
    slug: "stretch-jersey-tee",
    sku: "ZYL-TOP-TEE-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["tee", "jersey", "essential"],
    price: 195000,
    basePrice: 195000,
    mrp: 285000,
    cost: 85000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "A heavyweight jersey tee with a touch of stretch. Holds its shape wash after wash.",
    options: { Colour: ["Black", "Heather Grey"], Size: ["S", "M", "L", "XL"] },
    images: [
      { url: "/assets/ea97fe30fd8d1dfc.q.jpg", alt: "Stretch Jersey Tee", isFeatured: true },
      { url: "/assets/09789ab9b9e151f6.q.jpg", alt: "Stretch Jersey Tee detail", isFeatured: false }
    ]
  },
  {
    id: "p_utility_cargo",
    name: "Urban Utility Cargo",
    slug: "urban-utility-cargo",
    sku: "ZYL-BOT-CRG-01",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["cargo", "utility", "canvas"],
    price: 270000,
    basePrice: 270000,
    mrp: 360000,
    cost: 130000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "Roomy cargo trousers with angled utility pockets and a drawcord hem. Hard-wearing cotton canvas.",
    options: { Colour: ["Olive", "Black"], Size: ["30", "32", "34", "36"] },
    images: [
      { url: "/assets/2461720fa204607a.q.jpg", alt: "Urban Utility Cargo", isFeatured: true },
      { url: "/assets/39a84305ed8fadbc.q.jpg", alt: "Urban Utility Cargo detail", isFeatured: false }
    ]
  },
  {
    id: "p_boxy_tee",
    name: "Classic Boxy Tee",
    slug: "classic-boxy-tee",
    sku: "ZYL-TOP-BOX-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["tee", "boxy", "cotton"],
    price: 105000,
    basePrice: 105000,
    mrp: 135000,
    cost: 48000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "The everyday tee — boxy fit, dropped shoulder, midweight combed cotton in a clean solid.",
    options: { Colour: ["White", "Charcoal"], Size: ["XS", "S", "M", "L"] },
    images: [
      { url: "/assets/0d3fac373da0bd1f.q.jpg", alt: "Classic Boxy Tee", isFeatured: true },
      { url: "/assets/bbb4f22211e2dc51.q.jpg", alt: "Classic Boxy Tee detail", isFeatured: false }
    ]
  },
  {
    id: "p_smart_trousers",
    name: "Pleated Smart Trousers",
    slug: "pleated-smart-trousers",
    sku: "ZYL-BOT-PLT-01",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["trousers", "pleated", "formal"],
    price: 230000,
    basePrice: 230000,
    mrp: 300000,
    cost: 110000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "Double-pleated trousers with a tapered leg. Polished enough for work, easy enough for weekends.",
    options: { Colour: ["Charcoal", "Navy"], Size: ["30", "32", "34", "36"] },
    images: [
      { url: "/assets/9a83a5f92f7a34f6.q.jpg", alt: "Pleated Smart Trousers", isFeatured: true },
      { url: "/assets/19eee9f8e07093fd.q.jpg", alt: "Pleated Smart Trousers detail", isFeatured: false }
    ]
  },
  {
    id: "p_terry_shorts",
    name: "French Terry Shorts",
    slug: "french-terry-shorts",
    sku: "ZYL-BOT-SHT-01",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["shorts", "terry", "loungewear"],
    price: 120000,
    basePrice: 120000,
    mrp: 165000,
    cost: 55000,
    status: "published",
    labels: { newArrival: true, featured: false, bestSelling: false },
    description: "Loopback french terry shorts with a relaxed rise and side pockets. Off-duty essential.",
    options: { Colour: ["Cream", "Black"], Size: ["S", "M", "L"] },
    images: [
      { url: "/assets/b81e3eb6af13055d.q.jpg", alt: "French Terry Shorts", isFeatured: true },
      { url: "/assets/d4ddd6f6c7954c6b.q.jpg", alt: "French Terry Shorts detail", isFeatured: false }
    ]
  },
  {
    id: "p_oversized_hoodie",
    name: "Heavyweight Oversized Hoodie",
    slug: "heavyweight-oversized-hoodie",
    sku: "ZYL-TOP-HOD-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["hoodie", "fleece", "oversized"],
    price: 255000,
    basePrice: 255000,
    mrp: 330000,
    cost: 120000,
    status: "published",
    labels: { bestSelling: true, featured: true, newArrival: false },
    description: "Our signature 480gsm fleece hoodie. Oversized through the body with a double-lined hood and ribbed cuffs.",
    options: { Colour: ["Vintage Black", "Ash Grey"], Size: ["S", "M", "L", "XL"] },
    images: [
      { url: "/assets/eeac2757b9ee2e46.q.jpg", alt: "Heavyweight Oversized Hoodie", isFeatured: true },
      { url: "/assets/67866d53aaeebcac.q.jpg", alt: "Heavyweight Oversized Hoodie detail", isFeatured: false }
    ]
  },
  {
    id: "p_knit_sweater",
    name: "Patterned Knit Sweater",
    slug: "patterned-knit-sweater",
    sku: "ZYL-TOP-SWT-01",
    categoryId: "c_tops",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["sweater", "jacquard", "knit"],
    price: 135000,
    basePrice: 135000,
    mrp: 270000,
    cost: 65000,
    status: "published",
    labels: { bestSelling: true, featured: false, newArrival: false },
    description: "A jacquard-knit sweater in a tonal stripe. Soft-spun yarn with a regular fit.",
    options: { Colour: ["Monochrome Stripe"], Size: ["XS", "S", "M", "L"] },
    images: [
      { url: "/assets/3b9adec96400865c.q.jpg", alt: "Patterned Knit Sweater", isFeatured: true },
      { url: "/assets/ea5bdbd64c598cff.q.jpg", alt: "Patterned Knit Sweater detail", isFeatured: false }
    ]
  },
  {
    id: "p_quilted_bomber",
    name: "Quilted Bomber Jacket",
    slug: "quilted-bomber-jacket",
    sku: "ZYL-OUT-BOM-01",
    categoryId: "c_out",
    brand: "Zylo",
    gender: "Men",
    season: "SS26",
    tags: ["bomber", "jacket", "quilted"],
    price: 435000,
    basePrice: 435000,
    mrp: 540000,
    cost: 210000,
    status: "published",
    labels: { bestSelling: true, featured: true, newArrival: false },
    description: "A diamond-quilted bomber with matte hardware and ribbed trims. Warm without the bulk.",
    options: { Colour: ["Matte Black", "Olive"], Size: ["M", "L", "XL"] },
    images: [
      { url: "/assets/57e8f8ec76e792b1.q.jpg", alt: "Quilted Bomber Jacket", isFeatured: true },
      { url: "/assets/e2a028dd8bd0e7b5.q.jpg", alt: "Quilted Bomber Jacket detail", isFeatured: false }
    ]
  },
  {
    id: "p_puffer_vest",
    name: "Hooded Puffer Vest",
    slug: "hooded-puffer-vest",
    sku: "ZYL-OUT-VST-01",
    categoryId: "c_out",
    brand: "Zylo",
    gender: "Kids",
    season: "SS26",
    tags: ["vest", "puffer", "kids"],
    price: 135000,
    basePrice: 135000,
    mrp: 225000,
    cost: 65000,
    status: "published",
    labels: { bestSelling: true, featured: false, newArrival: false },
    description: "A lightweight puffer vest with a stowable hood. Layer it over knits when the mercury drops.",
    options: { Colour: ["Black", "Yellow"], Size: ["4Y", "6Y", "8Y", "10Y"] },
    images: [
      { url: "/assets/7f3fd1f72139111d.q.jpg", alt: "Hooded Puffer Vest", isFeatured: true },
      { url: "/assets/4a9712f500002e24.q.jpg", alt: "Hooded Puffer Vest detail", isFeatured: false }
    ]
  },
  {
    id: "p_leather_leggings",
    name: "Vegan Leather Leggings",
    slug: "vegan-leather-leggings",
    sku: "ZYL-BOT-LEG-01",
    categoryId: "c_bottoms",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["leggings", "leather", "stretch"],
    price: 225000,
    basePrice: 225000,
    mrp: 295000,
    cost: 105000,
    status: "published",
    labels: { bestSelling: true, featured: false, newArrival: false },
    description: "High-rise leggings in a matte vegan leather with four-way stretch and a clean ankle zip.",
    options: { Colour: ["Black"], Size: ["XS", "S", "M", "L"] },
    images: [
      { url: "/assets/54f4ed23bf992cef.q.jpg", alt: "Vegan Leather Leggings", isFeatured: true },
      { url: "/assets/365d4729feaf7290.q.jpg", alt: "Vegan Leather Leggings detail", isFeatured: false }
    ]
  },
  {
    id: "p_boxy_blazer",
    name: "Cropped Boxy Blazer",
    slug: "cropped-boxy-blazer",
    sku: "ZYL-OUT-BLZ-01",
    categoryId: "c_out",
    brand: "Zylo",
    gender: "Women",
    season: "SS26",
    tags: ["blazer", "tailored", "suit"],
    price: 390000,
    basePrice: 390000,
    mrp: 525000,
    cost: 180000,
    status: "published",
    labels: { bestSelling: true, featured: true, newArrival: false },
    description: "A cropped blazer with a boxy shoulder and single-button close. Sharp over anything.",
    options: { Colour: ["Black", "Pinstripe"], Size: ["XS", "S", "M", "L"] },
    images: [
      { url: "/assets/c71fd29c3338e4a5.q.jpg", alt: "Cropped Boxy Blazer", isFeatured: true },
      { url: "/assets/dac45b43062fbe55.q.jpg", alt: "Cropped Boxy Blazer detail", isFeatured: false }
    ]
  }
];
